echo "-------------------------------------------------------------------------------------------------------------------------------------------"
echo "-------------------------------------------------------------------------------------------------------------------------------------------"
echo "living-room-Nerfacto"
python Visual_Localization/VL_main.py camera-path --load-config outputs/living-room-seq-1-2/nerfacto/2023-09-14_225118/config.yml --dataset-path data/scenes/ --scene-name living-room --sequence-id 3 --MATCH-ALGORITHM LoFTR --NERF-ALGORITHM Nerfacto --output-path Visual_Localization/Workspace
python Visual_Localization/VL_main.py camera-path --load-config outputs/living-room-seq-1-2/nerfacto/2023-09-14_225118/config.yml --dataset-path data/scenes/ --scene-name living-room --sequence-id 4 --MATCH-ALGORITHM LoFTR --NERF-ALGORITHM Nerfacto --output-path Visual_Localization/Workspace
python Visual_Localization/VL_main.py camera-path --load-config outputs/living-room-seq-1-2/nerfacto/2023-09-14_225118/config.yml --dataset-path data/scenes/ --scene-name living-room --sequence-id 5 --MATCH-ALGORITHM LoFTR --NERF-ALGORITHM Nerfacto --output-path Visual_Localization/Workspace

python Visual_Localization/VL_main.py camera-path --load-config outputs/living-room-seq-1-2/nerfacto/2023-09-14_225118/config.yml --dataset-path data/scenes/ --scene-name living-room --sequence-id 3 --MATCH-ALGORITHM SuperGlue --NERF-ALGORITHM Nerfacto --output-path Visual_Localization/Workspace
python Visual_Localization/VL_main.py camera-path --load-config outputs/living-room-seq-1-2/nerfacto/2023-09-14_225118/config.yml --dataset-path data/scenes/ --scene-name living-room --sequence-id 4 --MATCH-ALGORITHM SuperGlue --NERF-ALGORITHM Nerfacto --output-path Visual_Localization/Workspace
python Visual_Localization/VL_main.py camera-path --load-config outputs/living-room-seq-1-2/nerfacto/2023-09-14_225118/config.yml --dataset-path data/scenes/ --scene-name living-room --sequence-id 5 --MATCH-ALGORITHM SuperGlue --NERF-ALGORITHM Nerfacto --output-path Visual_Localization/Workspace

python Visual_Localization/VL_main.py camera-path --load-config outputs/living-room-seq-1-2/nerfacto/2023-09-14_225118/config.yml --dataset-path data/scenes/ --scene-name living-room --sequence-id 3 --MATCH-ALGORITHM LightGlue --NERF-ALGORITHM Nerfacto --output-path Visual_Localization/Workspace
python Visual_Localization/VL_main.py camera-path --load-config outputs/living-room-seq-1-2/nerfacto/2023-09-14_225118/config.yml --dataset-path data/scenes/ --scene-name living-room --sequence-id 4 --MATCH-ALGORITHM LightGlue --NERF-ALGORITHM Nerfacto --output-path Visual_Localization/Workspace
python Visual_Localization/VL_main.py camera-path --load-config outputs/living-room-seq-1-2/nerfacto/2023-09-14_225118/config.yml --dataset-path data/scenes/ --scene-name living-room --sequence-id 5 --MATCH-ALGORITHM LightGlue --NERF-ALGORITHM Nerfacto --output-path Visual_Localization/Workspace

echo "-------------------------------------------------------------------------------------------------------------------------------------------"
echo "living-room-Instant-NGP"
python Visual_Localization/VL_main.py camera-path --load-config outputs/living-room-seq-1-2/instant-ngp/2023-09-14_230023/config.yml --dataset-path data/scenes/ --scene-name living-room --sequence-id 3 --MATCH-ALGORITHM LoFTR --NERF-ALGORITHM Instant-NGP --output-path Visual_Localization/Workspace
python Visual_Localization/VL_main.py camera-path --load-config outputs/living-room-seq-1-2/instant-ngp/2023-09-14_230023/config.yml --dataset-path data/scenes/ --scene-name living-room --sequence-id 4 --MATCH-ALGORITHM LoFTR --NERF-ALGORITHM Instant-NGP --output-path Visual_Localization/Workspace
python Visual_Localization/VL_main.py camera-path --load-config outputs/living-room-seq-1-2/instant-ngp/2023-09-14_230023/config.yml --dataset-path data/scenes/ --scene-name living-room --sequence-id 5 --MATCH-ALGORITHM LoFTR --NERF-ALGORITHM Instant-NGP --output-path Visual_Localization/Workspace

python Visual_Localization/VL_main.py camera-path --load-config outputs/living-room-seq-1-2/instant-ngp/2023-09-14_230023/config.yml --dataset-path data/scenes/ --scene-name living-room --sequence-id 3 --MATCH-ALGORITHM SuperGlue --NERF-ALGORITHM Instant-NGP --output-path Visual_Localization/Workspace
python Visual_Localization/VL_main.py camera-path --load-config outputs/living-room-seq-1-2/instant-ngp/2023-09-14_230023/config.yml --dataset-path data/scenes/ --scene-name living-room --sequence-id 4 --MATCH-ALGORITHM SuperGlue --NERF-ALGORITHM Instant-NGP --output-path Visual_Localization/Workspace
python Visual_Localization/VL_main.py camera-path --load-config outputs/living-room-seq-1-2/instant-ngp/2023-09-14_230023/config.yml --dataset-path data/scenes/ --scene-name living-room --sequence-id 5 --MATCH-ALGORITHM SuperGlue --NERF-ALGORITHM Instant-NGP --output-path Visual_Localization/Workspace

python Visual_Localization/VL_main.py camera-path --load-config outputs/living-room-seq-1-2/instant-ngp/2023-09-14_230023/config.yml --dataset-path data/scenes/ --scene-name living-room --sequence-id 3 --MATCH-ALGORITHM LightGlue --NERF-ALGORITHM Instant-NGP --output-path Visual_Localization/Workspace
python Visual_Localization/VL_main.py camera-path --load-config outputs/living-room-seq-1-2/instant-ngp/2023-09-14_230023/config.yml --dataset-path data/scenes/ --scene-name living-room --sequence-id 4 --MATCH-ALGORITHM LightGlue --NERF-ALGORITHM Instant-NGP --output-path Visual_Localization/Workspace
python Visual_Localization/VL_main.py camera-path --load-config outputs/living-room-seq-1-2/instant-ngp/2023-09-14_230023/config.yml --dataset-path data/scenes/ --scene-name living-room --sequence-id 5 --MATCH-ALGORITHM LightGlue --NERF-ALGORITHM Instant-NGP --output-path Visual_Localization/Workspace
